name: CI
on: ["push", "pull_request"]
jobs:
  build:
    name: Build, lint, test and send coverage to Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
